---
- hosts: localhost
  become: true
  vars_files: /tmp/ansible/vars.yml
  tasks:
    - import_tasks: /tmp/ansible/maven.yml
    - import_tasks: /tmp/ansible/sonarqube.yml
    - import_tasks: /tmp/ansible/docker.yml
    - import_tasks: /tmp/ansible/jenkins.yml
    - import_tasks: /tmp/ansible/firewall_web.yml
    - import_tasks: /tmp/ansible/firewall_sonar.yml

#- hosts: web
#  become: true
#  vars_files: /tmp/ansible/vars.yml
#  tasks:
#    - import_tasks: /tmp/ansible/web.yml
#    - import_tasks: /tmp/ansible/firewall_web.yml
...